<a href="https://colab.research.google.com/github/BhardwajArjit/Google-Colab/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Mon May 15 10:42:20 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P8    12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
print(torch.__version__)

2.0.0+cu118


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[3, 4],
                       [5, 6]])
MATRIX

tensor([[3, 4],
        [5, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([3, 4])

In [ ]:
MATRIX[1,1]

tensor(6)

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4,5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7563, 0.6440, 0.4980, 0.1914],
        [0.3964, 0.1990, 0.9691, 0.9734],
        [0.5884, 0.6649, 0.6798, 0.7581]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.2848, 0.3980, 0.5481, 0.9958, 0.0051, 0.3540, 0.7081, 0.8449,
          0.4017, 0.6919],
         [0.6120, 0.9352, 0.3401, 0.2298, 0.6225, 0.7450, 0.5799, 0.1766,
          0.1817, 0.0517],
         [0.8409, 0.7222, 0.0661, 0.3017, 0.3494, 0.2748, 0.5959, 0.5658,
          0.5277, 0.5679],
         [0.2839, 0.0024, 0.2999, 0.5507, 0.5382, 0.8608, 0.2825, 0.8094,
          0.7895, 0.7002],
         [0.0650, 0.0649, 0.3393, 0.6185, 0.5310, 0.2088, 0.0679, 0.6735,
          0.6060, 0.8313],
         [0.7635, 0.5652, 0.9795, 0.6895, 0.3296, 0.8454, 0.6572, 0.1913,
          0.9222, 0.5343],
         [0.6888, 0.7956, 0.8929, 0.1353, 0.8937, 0.4799, 0.3970, 0.0107,
          0.9192, 0.3535],
         [0.1361, 0.6993, 0.3597, 0.7539, 0.5163, 0.0289, 0.6182, 0.8801,
          0.0482, 0.2450],
         [0.8114, 0.1333, 0.8925, 0.6692, 0.2986, 0.4372, 0.4384, 0.1308,
          0.8226, 0.4083],
         [0.9914, 0.0655, 0.6840, 0.4977, 0.0078, 0.3924, 0.7068, 0.3508,
          0.7527,

In [ ]:
random_tensor.ndim

3

In [ ]:
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zero = torch.zeros(3,3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones = torch.ones(2, 2)
ones

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_16_tensor = torch.tensor([3, 4],
                               dtype = torch.float16,
                               device = None,
                               requires_grad = False)
float_16_tensor

tensor([3., 4.], dtype=torch.float16)

In [ ]:
t1 = torch.tensor([1, 2, 3])
t1 + 10

tensor([11, 12, 13])

In [ ]:
t1*10

tensor([10, 20, 30])

In [ ]:
t1 - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(t1, 10)

tensor([10, 20, 30])

In [ ]:
# matrix multiplication
t1 @ t1

tensor(14)

In [ ]:
x = torch.arange(0, 100, 10, dtype = torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
x.min(), x.max(), x.mean(), x.sum()

(tensor(0.), tensor(90.), tensor(45.), tensor(450.))

In [ ]:
x.argmax(), x.argmin()

(tensor(9), tensor(0))

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# should be compatible with no. of elements
x_reshaped = x.reshape([3, 3])
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
z = x.view([1, 9])
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_original = torch.rand(size = (224, 224, 3))
x_original.shape
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0, 0, 1]

tensor(2)

In [ ]:
x[0, 2, 2]

tensor(9)

In [ ]:
x[::]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
import numpy as np

In [ ]:
array = np.arange(1, 8)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
